name: getx_login
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #get x
  get: ^4.6.1
  get_storage: ^2.0.3

  #floor
  floor: ^1.2.0

  # api
  dio: ^4.0.4
  retrofit: ^3.0.1+1

  #toast
  fluttertoast: ^8.0.9

  #intro
  introduction_screen: ^3.0.0

  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  floor_generator: ^1.2.0
  flutter_lints: ^1.0.4
  retrofit_generator: ^3.0.1+1

flutter:
  uses-material-design: true
  assets:
    - assets/intro1.jpeg
    - assets/intro2.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
